function [FinalImage,chanelNames] =  MibiLoadMultiTiff(FileTif)
% function [FinalImage,chanelNames] =  MibiLoadMultiTiff(FileTif)
% Function gets the name of a multichannel tiff generated by the ionpath
% platform and returns 
% FinalImage: a 3d matrix of dimensions [X,Y,channel-number]
% chanelNames: a cell array of the channel names in the same order as the
% channels in FinalImage

InfoImage=imfinfo(FileTif);
mImage=InfoImage(1).Width;
nImage=InfoImage(1).Height;
NumberImages=length(InfoImage);
FinalImage=zeros(nImage,mImage,NumberImages);
chanelNamesFull=cell(NumberImages,1);
TifLink = Tiff(FileTif, 'r');
for i=1:NumberImages
   TifLink.setDirectory(i);
   FinalImage(:,:,i)=double(TifLink.read());
   chanelNames{i} = strtrim(regexprep(InfoImage(i).PageName,'\(\w*\)',''));
   chanelNames{i} = strip(chanelNames{i}); % 31.10 - removes spaces
   chanelNames{i} = strip(chanelNames{i},"left","b"); % 31.10 - removes batch staining addition
   chanelNames{i} = strip(chanelNames{i},"'"); % 31.10 - removes batch staining addition
end
for i = 1 : length(chanelNames)
    str = chanelNames{i};
    % 31.10 - replace / with - in AB names
    if strfind(str,'/') 
       str(strfind(str,'/')) = '-';
       chanelNames{i} = str;
    end
end

TifLink.close();

